// import {today,timeNow,getPatient} from 'helper';

const d = new Date();
function today() {
    return ((d.getDate() < 10) ? "0" : "") + d.getDate() + "/" + (((d.getMonth() + 1) < 10) ? "0" : "") + (d.getMonth() + 1) + "/" + d.getFullYear();
}

function timeNow() {
    return ((d.getHours() < 10) ? "0" : "") + d.getHours() + ":" + ((d.getMinutes() < 10) ? "0" : "") + d.getMinutes() + ":" + ((d.getSeconds() < 10) ? "0" : "") + d.getSeconds();
}

/**
 * Buy card transaction
 * @param {org1.healthcare.biznet.CreateAppointment} appointment
 * @transaction
 */

async function processAppointment(appointment){
    console.log("processAppointment: Start");
    // Get factory for creating new instance
    var datetime = today() + " @ " + timeNow();
    var factory = getFactory();
    var new_appointment = factory.newResource('org1.healthcare.biznet','Appointment',datetime+appointment.byPatient);
    
    new_appointment.appointmentTime = datetime;
    try{
        var patientParticipantRegistry =await getParticipantRegistry('org1.healthcare.biznet.Patient');
        var find_patient = await patientParticipantRegistry.get(appointment.byPatient);
        console.log("processAppointment: Got patient "+find_patient.Name);
        var doctorParticipantRegistry = await getParticipantRegistry('org1.healthcare.biznet.Doctor');
        var find_doctor = await doctorParticipantRegistry.get(appointment.forDoctor);
        console.log("processAppointment: Got doctor "+find_doctor.Name);
    } catch (err) {
        console.log("processAppointment Error : "+err.message);
        return;
    }
    
    new_appointment.byPatient = find_patient;
    new_appointment.forDoctor = find_doctor;
    new_appointment.completed = false

    let appointmentRegistry = await getAssetRegistry('org1.healthcare.biznet.Appointment');
    await appointmentRegistry.add(new_appointment);

    console.log("processAppointment: Added to registry");
    let event = getFactory().newEvent('org1.healthcare.biznet', 'AppointmentEvent');
    event.new_appointment = new_appointment;
    event.byPatient = appointment.byPatient;
    event.forDoctor = appointment.forDoctor;
    emit(event);
    // Have to add more to it
}

/**
 * Buy card transaction
 * @param {org1.healthcare.biznet.ResolveAppointment} res_appointment
 * @transaction
 */

async function processResolveAppointment(res_appointment){
    console.log("processResolveAppointment: Start");
    try{
        if((res_appointment.appointment.forDoctor.DoctorId != res_appointment.doctorId) || (res_appointment.appointment.completed != false) ) {
            console.log("processResolveAppointment Error: Doctor mismatch");
            return;
        }
    
        console.log("processResolveAppointment: Doctor Verified");

        var factory = getFactory();
        var new_report = factory.newResource('org1.healthcare.biznet','PatientReport',"P"+res_appointment.appointment.byPatient.PatiesntId+"A"+res_appointment.appointment.appointmentId);
        var new_prescription = factory.newResource('org1.healthcare.biznet','Prescription',"P"+res_appointment.appointment.byPatient.PatientId+"A"+res_appointment.appointment.appointmentId);
    
        console.log("processResolveAppointment: Entries Created in registry");
    
        new_report.ownerPatient = res_appointment.appointment.byPatient;
        new_report.creatingDoctor = res_appointment.appointment.forDoctor;
        new_report.reportMessage = res_appointment.reportMessage;
         
        new_report.canBeReferred = res_appointment.canBeReferred;  //added for referral

        let reportRegistry = await getAssetRegistry('org1.healthcare.biznet.PatientReport');
        

        new_prescription.forPatient = res_appointment.appointment.byPatient;
        new_prescription.byDoctor = res_appointment.appointment.forDoctor;
        var pharmacyParticipantRegistry = await getParticipantRegistry('org1.healthcare.biznet.Pharmacy');
        new_prescription.toPharmacy = await pharmacyParticipantRegistry.get(res_appointment.pharmacyId);
        new_prescription.PrescriptionText = res_appointment.PrescriptionText;
        let prescriptionRegistry = await getAssetRegistry('org1.healthcare.biznet.Prescription');

        await reportRegistry.add(new_report);
        console.log("processResolveAppointment: Report Filled");
        await prescriptionRegistry.add(new_prescription);
        console.log("processResolveAppointment: Prescription Filled");
        let appointmentRegistry = await getAssetRegistry('org1.healthcare.biznet.Appointment');
        res_appointment.appointment.completed = true;
        await appointmentRegistry.update(res_appointment.appointment);
    } 
    catch (err) {
        console.log("processResolveAppointment Error : "+err.message);
        return;
    }
}


/**
 * Process the Lab Report Generated by the Lab
 * @param {org1.healthcare.biznet.GenerateLabReport} generateLabReport
 * @transaction
 */

async function processLabReport(generateLabReport){
    var is_test_generated_by_doctor = false;
    console.log("Processing Lab Report Generated by Transaction " + generateLabReport.transactionId)
    var datetime = today() + " @ " + timeNow();
    var factory = getFactory();

    if (typeof generateLabReport.TestsReport == 'undefined')
    {
        error_message = "[ERROR] Processing Lab Report Generated by Transaction " + generateLabReport.transactionId + " Error: No lab report provided in the transaction";
        console.log(error_message);
        throw new Error(error_message)
    }
    try{
        var patientParticipantRegistry =await getParticipantRegistry('org1.healthcare.biznet.Patient');
        var find_patient = await patientParticipantRegistry.get(generateLabReport.PatientId);
        console.log("Processing Lab Report Generated by Transaction " + generateLabReport.transactionId + " Found patient " + generateLabReport.PatientId);
        if (typeof generateLabReport.DoctorId == 'undefined')
            console.log("Processing Lab Report Generated by Transaction " + generateLabReport.transactionId + " Test Not generated by Doctor");  

        else
        {
            var doctorParticipantRegistry = await getParticipantRegistry('org1.healthcare.biznet.Doctor');
            var find_doctor = await doctorParticipantRegistry.get(generateLabReport.DoctorId);
            is_test_generated_by_doctor = true;
            console.log("Processing Lab Report Generated by Transaction " + generateLabReport.transactionId + " Found doctor " + generateLabReport.DoctorId);
        }

        var labParticipantRegistry =await getParticipantRegistry('org1.healthcare.biznet.TestLab');
        var find_lab = await labParticipantRegistry.get(generateLabReport.LabId);
        console.log("Processing Lab Report Generated by Transaction " + generateLabReport.transactionId + " Found lab " + generateLabReport.LabId);


    } catch (err) 
    {
        console.log("[ERROR] Processing Lab Report Generated by Transaction " + generateLabReport.transactionId + " Error:" + err.message);
        return;
    }  
    var labReport = factory.newResource('org1.healthcare.biznet','LabReport',datetime+generateLabReport.PatientId+ generateLabReport.LabId); 
    labReport.report = generateLabReport.TestsReport;
    labReport.patient = find_patient;
    labReport.lab = find_lab;
    if(is_test_generated_by_doctor)
    {
        labReport.doctor = find_doctor;
    }
    let labReportRegistry = await getAssetRegistry('org1.healthcare.biznet.LabReport');
    await labReportRegistry.add(labReport);


    console.log("Processing complete for Transaction " + generateLabReport.transactionId);
}

/**
 * Patient chooses to allow Doctor to refer him/her to another Doctor
 * @param {org1.healthcare.biznet.AllowReferral} allow_referral
 * @transaction
 */

 //Yet to be validated
 async function AllowReferralOfReport(allow_referral) {
    console.log("Allowing Referral: START")
    try {
        
        var patientRegistry = await getParticipantRegistry('org1.healthcare.biznet.Patient');
        var reportRegistry = await getAssetRegistry('org1.healthcare.biznet.PatientReport')

        var patient = await patientRegistry.get(allow_referral.ownerPatient);
        console.log("Allow Referral: Got patient " + patient.Name);
        var report = await reportRegistry.get(allow_referral.Report)  
        console.log("Allow Referral: Got Report "+ report.reportId);

        allow_referral.Report.canBeReferred = 1;
        await reportRegistry.update(allow_referral.Report);

    } catch (err) {
        console.log("AllowReferralOfReport Error : " + err.message);
        return;
    }


 }

/**
 * Patient chooses NOT to allow Doctor to refer him/her to another Doctor
 * @param {org1.healthcare.biznet.AllowReferral} rev_referral
 * @transaction
 */

async function RevokeReferralOfReport(rev_referral) {
    console.log("Revoking Referral: START")
    try {
        var patientRegistry = await getParticipantRegistry('org1.healthcare.biznet.Patient');
        var reportRegistry = await getAssetRegistry('org1.healthcare.biznet.PatientReport')
        var patient = await patientRegistry.get(rev_referral.ownerPatient);
        console.log("Allow Referral: Got patient " + patient.Name);
        
        var report = await reportRegistry.get(rev_referral.Report)
        console.log("Allow Referral: Got Report "+ report.reportId);

        rev_referral.Report.canBeReferred = 0;
        await reportRegistry.update(rev_referral.Report);

    } 
    catch (err) {
        console.log("RevokeReferralOfReport Error : " + err.message);
        return;
    }

}

/**
 * Patient 
 * @param {org1.healthcare.biznet.ReferToAnotherDoctor} referral
 * @transaction
 */

 async function processReferral(referral) {
     console.log("Referral: START");
     try {
         var doctorRegistry = await getParticipantRegistry('org1.healthcare.biznet.Doctor')
         var reportRegistry = await getAssetRegistry('org1.healthcare.biznet.PatientReport')

         var oldDoctor = await doctorRegistry.get(referral.oldDoctor)
         console.log("processReferral: Got Old Doctor" + oldDoctor.Name)
         var newDoctor = await doctorRegistry.get(referral.newDoctor)
         console.log("processReferral: Got New Doctor" + newDoctor.Name)
         var report = await reportRegistry.get(referral.Report)
         console.log("Allow Referral: Got Report "+ report.reportId);

         //check if patient allows referral 
         if(report.canBeReferred == 0)
         throw new Error('Patient does not choose to be referred to another Doctor')
         else
         {
             referral.Report.creatingDoctor = newDoctor
             await reportRegistry.update(referral.Report);

         }
     }
     catch(err) {
         console.log("Error Message: " + err)
         return;
     }
 }

 
/**
 * Change in doctor request intiated by doctor (reqId,reportId,newDoctor,byDoctor)
 * @param {org1.healthcare.biznet.RequestDoctorChange} requestDocChange
 * @transaction
 */

async function createDcotorChangeRequest(requestDocChange) {
    console.log("DoctorChangeRequest: Start");
    try {
        var reportAssetRegsitry = await getAssetRegistry('org1.healthcare.biznet.PatientReport');
        var found_report = await reportAssetRegsitry.get(requestDocChange.reportId);
        


        // console.log("DoctorChangeRequest: ",found_report.creatingDoctor.getIdentifier(),requestDocChange.byDoctor.DoctorId);

        if(found_report.creatingDoctor.getIdentifier() != requestDocChange.byDoctor.DoctorId )
        {
            throw new Error("Creating and Requesting Doctor mismatch.");
        }
        console.log("DoctorChangeRequest: Doctor matched");
        var factory = getFactory();
        var new_request = factory.newResource('org1.healthcare.biznet','ReassignReportRequest',requestDocChange.reqId);

        new_request.newDoctor = requestDocChange.newDoctor;
        new_request.oldDoctor = requestDocChange.byDoctor;
        new_request.report = found_report;
        new_request.patientId = found_report.ownerPatient;
        console.log("DoctorChangeRequest: Filled Request");
        
        let requestResgistry = await getAssetRegistry('org1.healthcare.biznet.ReassignReportRequest');
        requestResgistry.add(new_request);

        console.log("DoctorChangeRequest: Request added to DB");

    } catch (err) {
        console.log("DoctorChangeRequest: Error: " + err)
        return;
    }
}

/**
 * Patients resolve on change in doctor request intiated by doctor (approve,toReassignRequest,byPatient
 * @param {org1.healthcare.biznet.ApproveRequestDoctorChange} approveReq
 * @transaction
 */

 async function apporveDoctorRequest(approveReq) {
    console.log("approveDocRequest: Start");
    try {
        if(approveReq.toReassignRequest.patientId.PatientId != approveReq.byPatient.PatientId )
        {
            throw new Error("Patient mismatch!!!");
        }
        
        if(approveReq.approve == true){
            console.log("approveDocRequest: Approve was accepted");
            let doctorParticipantRegistry = await getParticipantRegistry('org1.healthcare.biznet.Doctor');
            var newDoctor = await doctorParticipantRegistry.get(approveReq.toReassignRequest.newDoctor);
            console.log("approveDocRequest: Got new Doctor");

            approveReq.toReassignRequest.report.creatingDoctor = newDoctor;

            let reportRegistry = await getAssetRegistry('org1.healthcare.biznet.PatientReport');
            await reportRegistry.update(approveReq.toReassignRequest.report);
            console.log("approveDocRequest: Updated new doctor in report");
        }
        else
        {
            console.log("approveDocRequest: Approve was rejected");
        }
        let requestResgistry = await getAssetRegistry('org1.healthcare.biznet.ReassignReportRequest');
        console.log("approveDocRequest: Deleted request from the DB");
        await requestResgistry.remove(approveReq.toReassignRequest);
    } catch (err) {
    console.log("approveDocRequest: Error: " + err)
    return;
    }
 }